# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: makeupShop
    ports:
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  userserver:
    build: ./userserver
    restart: always
    depends_on:
       - db
    ports:
      - '5000:5000'
    volumes:
      - ./userserver/src:/src

  userclient:
    build: ./userclient
    restart: always
    links:
       - userserver
    ports:
      - '4000:4000'
    volumes:
      - ./userclient/src:/src

  adminserver:
    build: ./adminserver
    restart: always
    depends_on:
       - db
    ports:
      - '3000:3000'
    volumes:
      - ./adminserver/src:/src

  adminclient:
    build: ./adminclient
    restart: always
    links:
       - adminserver
    ports:
      - '2000:2000'
    volumes:
      - ./adminclient/src:/src

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  
# Names our volume
volumes:
  my-db:
      